### ISSUE TITLE
Getting status active pushed to HomeKit

### ISSUE THREAD

**Issue by DJay-X** [ch3rn1k/homebridge-multipurpose-kettle#6]
@ch3rn1k I hope you are well.
I am using your plugin now for the last weeks several times daily. Works absolutely reliable and I wouldn't want to miss it. 👍 

The small delay in first response is no big deal. It constantly takes about 4 seconds until the devices starts and also the temp info is showing. Siri also seems to have no problem. There is in general a "one moment" and than a "ok done". Not fast, but no time-out which is good. :) 

However I miss that HomeKit is not getting the Info that the kettle was turned on by the base manually. Maybe and without any hurry you will find a way to get this to work.

I use notifications to get an info when the kettle is turned on/off in general, but they not work at the moment when the kettle was used manually.

Thanks in advance for you consideration and your time.

All the best.
DJay

**Comment by ch3rn1k** [comment]
Hello, will check this, thanks

**Comment by ch3rn1k** [comment]
Hmmm, I have tested and everything looks good. All in all when I am doing custom "stop" method there is `updateCharacteristic` methods too. Hope this was fixed with latest `Interval` update (2.2.1) with 10 seconds delay.

**Comment by DJay-X** [comment]
Thanks. With turning on/off the kettle manually physically on the base in the kitchen, I still don't get a notification. 🤷🏼‍♂️
Only when opening Home or Eve App and pull to refresh the state is reflected.

**Comment by ch3rn1k** [comment]
Can you try version `2.2.2` please?

**Comment by DJay-X** [comment]
This seams to work now when turning the kettle on on the base in the kitchen, I get a notification from an automation I created. However in the log is nothing to see. But it works I think. :) 
I'll have an eye on it in the next days. 
Thanks a lot. 👍

**Comment by ch3rn1k** [comment]
Hey! How it's going? Works fine?

**Comment by DJay-X** [comment]
Hi. As always great work. I think this is now reliable. 
Every time the kettle is turned on manually on the base, the status is pushed and HomeKit was noticing it.
Finish boiling of course as well. 👍 

Jul 15 08:11:01 raspberrypi-3BPlus homebridge[11290]: [2020-7-15 8:11:01] [Wasserkocher] Received new command, working... [get_prop -> work_status]
Jul 15 08:11:01 raspberrypi-3BPlus homebridge[11290]: [2020-7-15 8:11:01] [Wasserkocher] DONE - "2"! [get_prop -> work_status ... miioPromise]
Jul 15 08:11:01 raspberrypi-3BPlus homebridge[11290]: [2020-7-15 8:11:01] [Messenger] Msg Wasserkocher start : Message sent to xxxxx (event : mikettle_start)


Only thing, the water is boiling to 100°C not 90° as set up in the config. 
But that is probably okay and due to the use on the base.

I think this request here can be closed. 🕺🏼✨🌐✨ 

Thanks again so much for your time and the willing to perfect your great plugin.

**Comment by ch3rn1k** [comment]
Thanks for your feedback! 👌🏻

About 100C - just change 'interval' back to 5 seconds and that will be fixed
